import clsx from 'clsx';
import { useTutorial } from '@/app/TutorialProvider';

/** Centered focal-image widths. `full` = no cap (legacy default). */
const SIZE: Record<string, string> = {
  sm: 'max-w-md',
  md: 'max-w-2xl',
  lg: 'max-w-4xl',
  full: 'max-w-none',
};

/**
 * Renders a tutorial-scoped image. `src` is a manifest id (resolved via the active tutorial's
 * asset map) or an explicit URL. If a referenced asset is missing (e.g. not yet generated by the
 * gemini-image skill), a labeled placeholder is shown so a slide never breaks.
 *
 * Images are always **centered** (`mx-auto`) — per the standard, a comic is a focal element that
 * sits between content (content → image → content), never pushed into a side column. Use `size` to
 * keep it at a sensible width so the content below stays in view.
 */
export function ImageBlock({
  src,
  alt,
  caption,
  size = 'full',
}: {
  src: string;
  alt: string;
  caption?: string;
  size?: 'sm' | 'md' | 'lg' | 'full';
}) {
  const tutorial = useTutorial();
  const isUrl = /[./]/.test(src);
  const resolved = isUrl ? src : tutorial.assets?.[src];
  const widthClass = SIZE[size] ?? SIZE.full;

  if (!resolved) {
    return (
      <figure className={clsx('mx-auto w-full shrink-0 rounded-lg border border-dashed border-border bg-surface-2 p-8 text-center', widthClass)}>
        <p className="font-display text-lg text-fg-muted">image: {src}</p>
        <p className="mt-1 font-mono text-xs text-fg-subtle">
          not generated yet — run <span className="text-accent">npm run gen:images</span>
        </p>
        {caption && <figcaption className="mt-2 text-sm text-fg-subtle">{caption}</figcaption>}
      </figure>
    );
  }

  return (
    <figure className={clsx('mx-auto w-full shrink-0 overflow-hidden rounded-lg border border-border bg-surface-2 shadow-sm', widthClass)}>
      <img src={resolved} alt={alt} className="h-auto w-full" />
      {caption && (
        <figcaption className="border-t border-border px-3 py-2 text-sm text-fg-subtle">{caption}</figcaption>
      )}
    </figure>
  );
}
